env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  key-spacing:
    - warn
    - {align: value}
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - {avoidEscape: true}
  semi:
    - error
    - always
  no-invalid-this:
    - error
  no-magic-numbers:
    - off
  no-multi-spaces:
    - error
    - {exceptions: {VariableDeclarator: true, ImportDeclaration: true}}
  no-sequences:
    - error
  no-warning-comments:
    - warn
  init-declarations:
    - error
    - always
  no-shadow:
    - error
  no-undef:
    - error
  no-process-env:
    - error
  array-bracket-spacing:
    - error
  block-spacing:
    - error
  brace-style:
    - error
  comma-style:
    - error
  consistent-this:
    - error
    - self
  keyword-spacing:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  object-curly-spacing:
    - error
  space-infix-ops:
    - error
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
  no-var:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - warn
  prefer-template:
    - error