resources:
  - name: node-blip-client
    type: git
    source:
      uri: https://www.github.com/groupby/node-blip-client.git
      branch: concourse
jobs:
  - name: test
    plan:
      - get: node-blip-client
      - task: install
        file: node-blip-client/concourse/task-npm-install.yml
      - task: install
        file: node-blip-client/concourse/task-npm-install-gulp.yml
      - task: test
        file: node-blip-client/concourse/task-gulp-test.yml